### ISSUE TITLE
Remove parcel as dependency as it is causing issues with npm i

### ISSUE THREAD

**Issue by mjwebb1993** [savvy-coders/savvy-spa-starter#11]
Parcel is out of date and causes npm i to crash

**Comment by matsinet** [comment]
I would recommend removing `parcel` from the dependencies all together.

**Comment by mjwebb1993** [comment]
Good point, I agree

**Comment by mjwebb1993** [comment]
> I would recommend removing `parcel` from the dependencies all together.

Good point, I agree

**Comment by matsinet** [comment]
https://github.com/savvy-coders/savvy-spa-starter/pull/13
